#:include main_screen.kv
#:include booked_tasks.kv


ScreenManager:
    id: screen_manager
    HomeScreen:
        name: "main_screen"
        id: main_screen
    BookedTasks:
        name: "booked_tasks"
        id: booked_tasks
    CompletedTasks:
        name: "completed_tasks"
        id: completed_tasks
    MyTeam:
        name: "team"
        id: team
    Stats:
        name: "stats"
        id: stats
    Settings:
        name: "settings"
        id: settings
